name: go_getter
description: "implementation of a \"GoGetter\" game from the Smart Games series"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flame: ^1.16.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/block1.png
    - assets/images/block2.png
    - assets/images/block3.png
    - assets/images/block4.png
    - assets/images/block5.png
    - assets/images/block6.png
    - assets/images/block7.png
    - assets/images/block8.png
    - assets/images/block9.png
    - assets/images/board.png
