name: go_getter
description: "implementation of a \"GoGetter\" game from the Smart Games series"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flame: ^1.16.0
  flame_audio: ^2.10.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  graphs: ^2.3.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/board/
    - assets/images/UI/
    - assets/images/levels/
    - assets/audio/music/
    - assets/audio/effects/
    - assets/levels/starter/
    - assets/levels/junior/
    - assets/levels/master/
    - assets/levels/expert/

